import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import React from "react";

import styles from "../styles/About.module.css";

interface props {}
const About: React.FC<props> = (props) => {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>About - Next.js Google!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/G_Logo.svg" />
      </Head>

      <header className={styles.header}>
        <Image
          className={styles.logo}
          onClick={() => router.push("/")}
          src="/Google_logo.svg"
          width="100"
          height="50"
        />
        <h2>About</h2>
        <div />
      </header>
      <div className={styles.container}>
        <h1>Hi there 👋</h1>

        <p>
          <span className={styles.intro}>My Name is Christopher</span> and I
          made this Google look-a-like as a portfolio project for my resume. I
          built it using <b> Next.js</b> (a React Framework) and{" "}
          <b>pure CSS 3</b>. It also utilizes the google custom search api which
          can be found{" "}
          <a
            className={styles.link}
            href="https://developers.google.com/custom-search/"
          >
            here
          </a>
          .
        </p>
        <p>
          <span className={styles.indent}>
            If you like what you see you can checkout
          </span>{" "}
          more projects on my{" "}
          <a className={styles.link} href="https://github.com/chrisdemahy">
            Github
          </a>{" "}
          and some of my posts on{" "}
          <a
            className={styles.link}
            href="https://linkedin.com/in/christopherdemahy"
          >
            {" "}
            LinkedIn
          </a>
          . You can also follow my twitter handle{" "}
          <a className={styles.link} href="https://twitter.com/chrisdemahy">
            @ChrisDemahy
          </a>
          .
        </p>
      </div>
    </div>
  );
};

export default About;
